version: "2"
checks:
  method-lines:
    enabled: false
  similar-code:
    enabled: false
plugins:
  eslint:
    enabled: true
    checks:
      jsx-a11y/anchor-is-valid:
        enabled: false
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
